---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/unifi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
