---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.54.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter
  interval: 30m
  values:
    fullnameOverride: node-exporter
    image:
      registry: quay.io
      repository: prometheus/node-exporter
    prometheus:
      monitor:
        enabled: true
        jobLabel: app.kubernetes.io/instance
        relabelings:
          - action: replace
            regex: (.*)
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            replacement: $1
            targetLabel: kubernetes_node
          - action: replace
            regex: (.*)
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            replacement: $1
            targetLabel: nodename
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_host_ip
            targetLabel: instance
    resources:
      requests:
        cpu: 23m
        memory: 64M
      limits:
        memory: 64M
    hostNetwork: false
