---
# kubeProxyReplacement enables kube-proxy replacement in Cilium BPF datapath
kubeProxyReplacement: "strict"

k8sServiceHost: 10.1.10.20
k8sServicePort: 6443

ipam:
  mode: "kubernetes"

bgp:
  enabled: false
  announce:
    loadbalancerIP: true

hubble:
  enabled: false

ipv6:
  enabled: false
