---
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-r2"
stringData:
  RESTIC_REPOSITORY: "s3:${R2_REPOSITORY}/volsync/${APP}"
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-r2
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 5 * * *"
  restic:
    copyMethod: Snapshot
    repository: ${APP}-volsync-r2
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-local-hostpath}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpoo}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    pruneIntervalDays: 7
    retain:
      daily: 7
