---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/darkstar/k8s/apps/networking/external-dns/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
