---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.13.5
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  values:
    clusterName: "${SECRET_CLUSTER_NAME}"
    operatorNamespace: "rook-ceph"
    toolbox:
      enabled: false
    monitoring:
      enabled: true
      createPrometheusRules: true
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
      osd_pool_default_size = 1
      mon_warn_on_pool_no_redundancy = false
      bdev_flock_retry = 20
      bluefs_buffered_io = false
      mon_data_avail_warn = 10
    cephClusterSpec:
      cephVersion:
        image: "quay.io/ceph/ceph:v18.2.0"
      disruptionManagement:
        managePodBudgets: true
      healthCheck:
        daemonHealth:
          mon:
            interval: 45s
            timeout: 600s
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
      network:
        provider: host
      priorityClassNames:
        all: system-node-critical
        mgr: system-cluster-critical
      resources:
        mgr:
          requests:
            cpu: "125m"
            memory: "512Mi"
          limits:
            memory: "2Gi"
        mon:
          requests:
            cpu: "49m"
            memory: "512Mi"
          limits:
            memory: "1Gi"
        osd:
          requests:
            cpu: "442m"
            memory: "2Gi"
          limits:
            memory: "6Gi"
        mgr-sidecar:
          requests:
            cpu: "49m"
            memory: "128Mi"
          limits:
            memory: "256Mi"
        crashcollector:
          requests:
            cpu: "15m"
            memory: "64Mi"
          limits:
            memory: "64Mi"
        logcollector:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            memory: "1Gi"
        cleanup:
          requests:
            cpu: "250m"
            memory: "100Mi"
          limits:
            memory: "1Gi"
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: "/"
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: alpha
            devices:
              - name: "/dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b45f4bd5e"
    ingress:
      dashboard:
        ingressClassName: ingress-nginx-int
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        host:
          name: &host rook.${SECRET_DOMAIN_PROXY}
          path: "/"
        tls:
          - hosts:
              - *host

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 1
            requireSafeReplicaSize: false
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: false
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: true
      deletionPolicy: Delete

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 1
              requireSafeReplicaSize: false
          dataPools:
            - failureDomain: host
              replicated:
                size: 1
                requireSafeReplicaSize: false
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: "35m"
                memory: "1Gi"
              limits:
                memory: "3Gi"
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-filesystem
      isDefault: false
      deletionPolicy: Delete
