---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: dockhand-apollo
spec:
  appProtocols:
    - gateway.envoyproxy.io/ws
    - gateway.envoyproxy.io/wss
  endpoints:
    - fqdn:
        hostname: apollo.lan.starstreak.net
        port: 3000
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: dockhand-gravity
spec:
  appProtocols:
    - gateway.envoyproxy.io/ws
    - gateway.envoyproxy.io/wss
  endpoints:
    - fqdn:
        hostname: gravity.lan.starstreak.net
        port: 3000
