[env]
# Directory paths
ROOT_DIR = "{{config_root}}"
# File paths
KUBECONFIG            = "{{config_root}}/kubernetes/darkstar/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.github/.minijinja.toml"
TALOSCONFIG           = "{{config_root}}/infrastructure/talos/darkstar/clusterconfig/talosconfig"
# Ansible
VIRTUAL_ENV              = "{{config_root}}/.venv"
ANSIBLE_COLLECTIONS_PATH = "{{config_root}}/.venv/galaxy"
ANSIBLE_ROLES_PATH       = "{{config_root}}/.venv/galaxy/ansible_roles"
ANSIBLE_VARS_ENABLED     = "host_group_vars"

[tools]
ansible-core                   = '2.21.2'
"github:DopplerHQ/cli"         = '3.76.0'
"github:home-operations/flate" = '0.4.10'
flux2                          = '2.9.2'
helm                           = '4.2.3'
helmfile                       = '1.7.1'
jq                             = '1.8.2'
k9s                            = '0.51.0'
kubectl                        = '1.36.2'
kustomize                      = '5.8.1'
"aqua:mitsuhiko/minijinja"     = '2.21.0'
talhelper                      = '3.1.13'
talosctl                       = '1.13.6'
task                           = '3.52.0'
