---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTERS_DIR: "{{.PROJECT_DIR}}/clusters"

includes:
  ansible:
    taskfile: ".taskfiles/ansible"
    dir: .taskfiles/ansible
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  k8s:
    taskfile: .taskfiles/k8s
    dir: .taskfiles/k8s
  rook:
    taskfile: ".taskfiles/rook"
    dir: .taskfiles/rook
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops
  talos:
    taskfile: ".taskfiles/talos"
    dir: .taskfiles/talos
  volsync:
    taskfile: ".taskfiles/volsync"
    dir: .taskfiles/volsync

tasks:
  default:
    silent: true
    cmds:
      - task -l
