{
 "title": "ZFS Pool / Datasets",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(zfs_exporter_build_info{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(zfs_exporter_build_info{location=~\"$location\"}[$__range]))"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=~\"$instance\"})"
    }
   },
   { "name": "dataset_filter", "label": "Dataset selector" },
   {
    "name": "type",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=~\"$instance\", pool=\"$pool\"})"
    }
   },
   { "name": "low_limit", "label": "Min volume size", "query": "10" },
   {
    "name": "limit_suffix",
    "label": "Size suffix",
    "query": "Byte : 1, KB : 1024, MB : 1048576, GB : 1073741824, TB : 1099511627776"
   },
   {
    "name": "dataset",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=~\"$instance\", pool=\"$pool\", name=~\".*(${dataset_filter}).*\", type=~\"$type\", type=\"filesystem\"} or zfs_dataset_volume_size_bytes{instance=~\"$instance\", pool=\"$pool\", name=~\".*(${dataset_filter}).*\"} > ($low_limit + 0) * $limit_suffix)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 20, "w": 22, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pool, name, type) (zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (\r\n  zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"} /\r\n  on (instance, pool) group_left()\r\n  zfs_pool_size_bytes{instance=\"$instance\", pool=~\"$pool\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_logical_used_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_quota_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})\r\nor\r\nmax by(pool, name, type) (zfs_dataset_volume_size_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_written_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_referenced_reservation_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (zfs_dataset_available_bytes{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (\r\n  zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}\r\n  or\r\n  zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pool, name, type) (\r\nzfs_dataset_snapshot_count_total{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "created (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(name) (\r\n  max_over_time(zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}[$__interval])\r\n  or\r\n  max_over_time(zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$dataset\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Used delta (logical)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (delta(zfs_dataset_logical_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__rate_interval])) * ($__interval_ms / $__rate_interval_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota %",
   "type": "timeseries",
   "description": "When quota is not set, this is expected to be empty.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(name) (\r\nmax_over_time(zfs_dataset_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) /\r\n(max_over_time(zfs_dataset_quota_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ref Quota %",
   "type": "timeseries",
   "description": "When ref quota is not set, this is expected to be empty.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(name) (\r\nmax_over_time(zfs_dataset_referenced_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) /\r\n(last_over_time(zfs_dataset_referenced_quota_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume allocated %",
   "type": "timeseries",
   "description": "When volumes are not listed, this is expected to be empty.\nAmount of storage logically allocated to volume. Volumes without discard can have this value artificially high.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(name) (\r\nmax_over_time(zfs_dataset_logical_used_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval]) /\r\nmax_over_time(zfs_dataset_volume_size_bytes{instance=\"$instance\", pool=~\"$pool\", type=~\"$type\", name=~\"$dataset\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Read Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "written total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval])) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read IO average size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dataset) (\r\n  rate(node_zfs_zpool_dataset_nread{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) /\r\n  (rate(node_zfs_zpool_dataset_reads{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(dataset) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IO average size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dataset) (\r\n  rate(node_zfs_zpool_dataset_nwritten{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) /\r\n  (rate(node_zfs_zpool_dataset_writes{instance=\"$instance\", dataset=~\"$dataset\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}