{
 "title": "ZFS Pool Overview",
 "description": "ZFS monitoring dashboard",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(zfs_exporter_build_info{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(last_over_time(zfs_exporter_build_info{location=~\"$location\"}[$__range]))"
    }
   },
   { "name": "pool_filter" },
   {
    "name": "pool",
    "query": {
     "query": "query_result(zfs_dataset_used_bytes{instance=~\"$instance\", pool=~\".*($pool_filter).*\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool List",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "max by(location, instance, pool) (zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (label_replace(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}, \"pool\", \"$1\", \"zpool\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (zfs_pool_fragmentation_ratio{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (zfs_pool_deduplication_ratio{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(instance, pool) (\r\n  zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\"}\r\n  or\r\n  # zfs_dataset_creation was used before official support for creation was added\r\n  zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\"}\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool state",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(instance, zpool, state) (\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"online\"}[$__interval]) == 1) * 2\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"offline\"}[$__interval]) == 1) * 3\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"removed\"}[$__interval]) == 1) * 4\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"suspended\"}[$__interval]) == 1) * 5\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"degraded\"}[$__interval]) == 1) * 6\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"faulted\"}[$__interval]) == 1) * 7\r\nor\r\nmax without(state) (max_over_time(node_zfs_zpool_state{instance=~\"$instance\", zpool=~\"$pool\", state=\"unavail\"}[$__interval]) == 1) * 8\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "last loaded (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_load_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "created (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "# max_over_time to get the newest creation date in case pool with the same name was recreated\r\n# using name=~\"$pool\" selects root dataset of apool, which is always the oldest dataset\r\n$__to / 1000 - min by(instance, pool) (\r\n  max_over_time(zfs_dataset_creation_timestamp{instance=~\"$instance\", pool=~\"$pool\", name=~\"$pool\"}[$__interval])\r\n  or\r\n  # zfs_dataset_creation was used before official support for creation was added\r\n  max_over_time(zfs_dataset_creation{instance=~\"$instance\", pool=~\"$pool\", name=~\"$pool\"}[$__interval])\r\n)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "dedup ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (avg_over_time(zfs_pool_deduplication_ratio{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "exporter version history",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "group by(instance, version) (label_replace(last_over_time(zfs_exporter_build_info{instance=~\"$instance\"}[$__interval]), \"version\", \"<missing>\", \"version\", \"\"))\r\nor on()\r\n(\r\n  vector(0) unless on() last_over_time(zfs_exporter_build_info{instance=~\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fragmentation ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (avg_over_time(zfs_pool_fragmentation_ratio{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (max_over_time(zfs_pool_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "used %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (\r\nmax_over_time(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval])\r\n/\r\nmax_over_time(zfs_pool_size_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval])\r\n)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance, pool) (delta(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__rate_interval])) * ($__interval_ms / $__rate_interval_ms)",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "used bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, pool) (max_over_time(zfs_pool_allocated_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  {
   "title": "free bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min by(instance, pool) (min_over_time(zfs_pool_free_bytes{instance=~\"$instance\", pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{pool}}"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Read (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(node_zfs_zpool_dataset_nread{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Write (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(node_zfs_zpool_dataset_nwritten{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Read (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Write (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Read (vdev) without scan (approximation, divided by parity coefficient)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\n  # for single-device vdevs get exact value\r\n  rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"disk-.*\"}[$__rate_interval])\r\n  or\r\n  # for mirror vdevs get average between leaf vdevs\r\n  avg by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"mirror-.*\"}[$__rate_interval]))\r\n  or\r\n  # for raid-z vdevs get avg * (count - 1)\r\n  (\r\n    avg by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz1-.*\"}[$__rate_interval]))\r\n    *\r\n    (-1 + count by(instance, zpool, vdev) (zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz1-.*\"}))\r\n  )\r\n  or\r\n  # for raid-z2 vdevs get avg * (count - 2)\r\n  (\r\n    avg by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz2-.*\"}[$__rate_interval]))\r\n    *\r\n    (-2 + count by(instance, zpool, vdev) (zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz2-.*\"}))\r\n  )\r\n  or\r\n  # for raid-z3 vdevs get avg * (count - 3)\r\n  (\r\n    avg by(instance, zpool, vdev) (rate(zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz3-.*\"}[$__rate_interval]))\r\n    *\r\n    (-3 + count by(instance, zpool, vdev) (zfs_vdev_bytes{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\", vdev=~\"raidz3-.*\"}))\r\n  )\r\n)\r\n-\r\nsum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 78 },
   "options": {
    "content": "zfs_exporter for vdevs doesn't have info about l2arc devices,\r\nso vdev read/write speed includes only main disks."
   }
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Read IOPS (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(node_zfs_zpool_dataset_reads{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Write IOPS (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(node_zfs_zpool_dataset_writes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Read IOPS (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", type=\"read\", path!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "Write IOPS (vdev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (rate(zfs_vdev_ops{instance=~\"$instance\", zpool=~\"$pool\", type=\"write\", path!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "trim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "trim state",
   "type": "state-timeline",
   "description": "TRIM is performed per-vdev. This graph is an aggregation that show \"the worst\" TRIM state across all disks in a pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "min by(instance, zpool) (\r\nmin_over_time(zfs_vdev_trim_state{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval])\r\nand\r\n(min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 0)\r\nor\r\n(min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 1) * 10\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim processed bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (\r\nrate(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__rate_interval])\r\nand\r\n(min_over_time(zfs_vdev_trim_unsupported{instance=~\"$instance\", zpool=~\"$pool\", path!=\"\"}[$__interval]) == 0)\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim start time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0) * 1000",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim: completed %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool) (\r\navg_over_time(zfs_vdev_trim_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n/\r\n(max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless trim ran in time range. \"calc\" is a very rough approximation, it is only correct when you zoom in. If you have a special recording rule, you will also have \"record\" value which is always correct.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (time() - (max_over_time(zfs_vdev_trim_action_time{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0))\r\n*\r\n(1 / min by (instance, zpool) (min_over_time(zfs_vdev_trim_active_processed_ratio{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) - 1)",
     "legendFormat": "{{instance}}/{{zpool}} (calc)"
    },
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}} (record)"
    }
   ]
  },
  {
   "title": "trim estimated size",
   "type": "state-timeline",
   "description": "size of the relevant data in the pool when scan was started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_vdev_trim_estimated_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "trim errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (max_over_time(zfs_vdev_trim_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  { "title": "scan: scrub/resilver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "scan state",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "min by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) > 1)\r\nor\r\n(\r\ngroup by(instance, zpool) (max_over_time(zfs_pool_scan_scrub_pause{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0) + 20\r\n)\r\nor\r\n(\r\nmin by(instance, zpool) (min_over_time(zfs_pool_scan_func{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) + 10\r\nand\r\nmin by(instance, zpool) (min_over_time(zfs_pool_scan_state{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) <= 1\r\n)\r\nor\r\ngroup by(instance, zpool) (min_over_time(zfs_pool_config_txg{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])) * 30",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "notes",
   "type": "text",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 137 },
   "options": {
    "content": "Scan info is empty for pools\nthat have never run\nscrub or resilver\nin their lifetime.\n\n`examined` is about\ngathering metadata for scan.\n\n`issued` is actually\nreading/writing data."
   }
  },
  {
   "title": "scan errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, zpool) (max_over_time(zfs_pool_scan_errors{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "last scan duration",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (\r\n(max_over_time(zfs_pool_scan_end_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)\r\n-\r\nmax_over_time(zfs_pool_scan_start_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval])\r\n)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: processed byte rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_processed_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: estimated size",
   "type": "state-timeline",
   "description": "size of the relevant data in the pool when scan was started",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_pool_scan_to_examine_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: to process bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_pool_scan_to_process_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan end time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_end_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]) != 0)",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: examined byte rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_examined_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_start_time_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: examine completed %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool) (avg_over_time(zfs_pool_scan_examined_ratio{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan pass start time (ago)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$__to / 1000 - max by(instance, zpool) (max_over_time(zfs_pool_scan_pass_start_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued byte rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance, zpool) (rate(zfs_pool_scan_issued_bytes{instance=~\"$instance\", zpool=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless scan ran in time range. \"calc\" is a very rough approximation, it is only correct when you zoom in. If you have a special recording rule, you will also have \"record\" value which is always correct.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_pool_scan_issue_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: issued completed %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (instance, zpool) (avg_over_time(zfs_pool_scan_issued_ratio{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  },
  {
   "title": "scan: examined: estimated remaining time",
   "type": "timeseries",
   "description": "Empty, unless scan ran in time range. \"calc\" is a very rough approximation, it is only correct when you zoom in. If you have a special recording rule, you will also have \"record\" value which is always correct.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, zpool) (max_over_time(zfs_pool_scan_examine_estimated_remaining_seconds{instance=~\"$instance\", zpool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{instance}}/{{zpool}}"
    }
   ]
  }
 ]
}