{
 "title": "ZFS ARC Statistics",
 "description": "ZFS metrics as extracted by node_exporter",
 "tags": [
  "ZFS",
  "node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "location",
    "query": {
     "query": "query_result(group by(location) (last_over_time(node_zfs_arc_size{}[$__range])))"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(last_over_time(node_zfs_arc_size{location=~\"$location\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ARC size (high level)",
   "type": "timeseries",
   "description": "arc_c == target ?==? arc current",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(avg_over_time(node_zfs_arc_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ARC Size"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_c{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ARC Target"
    },
    {
     "expr": "max(max_over_time(node_zfs_arc_c_max{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ARC Max"
    },
    {
     "expr": "min(min_over_time(node_zfs_arc_c_min{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ARC Min"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=\"$instance\"})",
     "legendFormat": "node total"
    },
    {
     "expr": "max(node_zfs_arc_arc_sys_free{instance=\"$instance\"})",
     "legendFormat": "arc sys free"
    },
    {
     "expr": "# seems like in ZFS arc_sys_free targets MemFree, without accounting for Buffers and Cached\r\nmax(avg_over_time(node_memory_MemFree_bytes{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "node free"
    },
    {
     "expr": "max(\r\nnode_memory_MemFree_bytes{instance=\"$instance\"}\r\n+\r\nnode_memory_Buffers_bytes{instance=\"$instance\"}\r\n+\r\nnode_memory_Cached_bytes{instance=\"$instance\"}\r\n)",
     "legendFormat": "free+cache"
    }
   ]
  },
  {
   "title": "ARC size (percent)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\navg_over_time(node_zfs_arc_size{instance=\"$instance\"}[$__interval])\r\n/\r\navg_over_time(node_zfs_arc_c{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "Size / Target"
    },
    {
     "expr": "max(\r\navg_over_time(node_zfs_arc_c{instance=\"$instance\"}[$__interval])\r\n/\r\nmax_over_time(node_zfs_arc_c_max{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "Target / Max"
    },
    {
     "expr": "max(\r\nmax_over_time(node_zfs_arc_c_max{instance=\"$instance\"}[$__interval])\r\n/\r\nmax_over_time(node_memory_MemTotal_bytes{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "Max / Node total"
    }
   ]
  },
  {
   "title": "ARC hit rate notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 16 },
   "options": {
    "content": "- `data` and `meta`: data is already in ARC\n- `L2`: data is already in L2ARC\n- `zfetch`: data access is predictable\n- `adaptive prefetch`: data is prefetched using heuristic\n- `prescient prefetch`: data is prefetched withtout heuristics\n- - prescient prefetch is rarely used (so it has 0% hit rate in graph) but hit rate is usually 100%\n"
   }
  },
  {
   "title": "ARC hit %",
   "type": "timeseries",
   "description": "When there is no demand, result value will be 0%",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n(\r\n  rate(node_zfs_arc_demand_data_hits{instance=\"$instance\"}[$__rate_interval])\r\n)\r\n/\r\n(\r\n  rate(node_zfs_arc_demand_data_hits{instance=\"$instance\"}[$__rate_interval])\r\n  +\r\n  rate(node_zfs_arc_demand_data_misses{instance=\"$instance\"}[$__rate_interval])\r\n  +\r\n  1e-6\r\n)\r\n)",
     "legendFormat": "data"
    },
    {
     "expr": "max(\r\n(\r\n  rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\"}[$__rate_interval])\r\n)\r\n/\r\n(\r\n  rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\"}[$__rate_interval])\r\n  +\r\n  rate(node_zfs_arc_demand_metadata_misses{instance=\"$instance\"}[$__rate_interval])\r\n  +\r\n  1e-6\r\n)\r\n)",
     "legendFormat": "metadata"
    },
    {
     "expr": "max(\r\n(rate(node_zfs_arc_l2_hits{instance=\"$instance\"}[$__rate_interval]))\r\n/\r\n(rate(node_zfs_arc_l2_hits{instance=\"$instance\"}[$__rate_interval]) + rate(node_zfs_arc_l2_misses{instance=\"$instance\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "L2"
    },
    {
     "expr": "max(\r\n(rate(node_zfs_zfetch_hits{instance=\"$instance\"}[$__rate_interval])) / (rate(node_zfs_zfetch_hits{instance=\"$instance\"}[$__rate_interval]) + rate(node_zfs_zfetch_misses{instance=\"$instance\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "zfetch"
    },
    {
     "expr": "max(\r\n(rate(node_zfs_arc_demand_hit_predictive_prefetch{instance=\"$instance\"}[$__rate_interval])) / (rate(node_zfs_arc_predictive_prefetch{instance=\"$instance\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "adaptive prefetch"
    },
    {
     "expr": "max(\r\n(rate(node_zfs_arc_demand_hit_prescient_prefetch{instance=\"$instance\"}[$__rate_interval])) / (rate(node_zfs_arc_prescient_prefetch{instance=\"$instance\"}[$__rate_interval]) + 1e-6)\r\n)",
     "legendFormat": "prescient prefetch"
    }
   ]
  },
  {
   "title": "ARC hits and misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_zfs_arc_demand_data_hits{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "data hit"
    },
    {
     "expr": "sum(rate(node_zfs_arc_demand_data_misses{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "data miss"
    },
    {
     "expr": "sum(rate(node_zfs_arc_demand_metadata_hits{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "meta hit"
    },
    {
     "expr": "sum(rate(node_zfs_arc_demand_metadata_misses{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "meta miss"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_hits{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "L2 hit"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_misses{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "L2 miss"
    },
    {
     "expr": "sum(rate(node_zfs_arc_demand_hit_predictive_prefetch{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "adaptive prefetch hit"
    },
    {
     "expr": "sum(\r\nrate(node_zfs_arc_predictive_prefetch{instance=\"$instance\"}[$__rate_interval]) - rate(node_zfs_arc_demand_hit_predictive_prefetch{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "adaptive prefetch miss"
    },
    {
     "expr": "sum(rate(node_zfs_arc_demand_hit_prescient_prefetch{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "prescient prefetch hit"
    },
    {
     "expr": "sum(\r\nrate(node_zfs_arc_prescient_prefetch{instance=\"$instance\"}[$__rate_interval]) - rate(node_zfs_arc_demand_hit_prescient_prefetch{instance=\"$instance\"}[$__rate_interval])\r\n)",
     "legendFormat": "prescient prefetch miss"
    }
   ]
  },
  {
   "title": "ARC dirty bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\nmax_over_time(node_zfs_arc_anon_size{instance=\"$instance\"}[$__interval])\r\n+\r\nmax_over_time(node_zfs_arc_arc_tempreserve{instance=\"$instance\"}[$__interval])\r\n-\r\nmin_over_time(node_zfs_arc_arc_loaned_bytes{instance=\"$instance\"}[$__interval])\r\n)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "ARC size details (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(avg_over_time(node_zfs_arc_dnode_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "dnode"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_dbuf_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "dbuf"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_hdr_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Headers"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_abd_chunk_waste_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "ABD waste"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_metadata_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Meta"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_l2_hdr_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "L2 headers"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_data_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "arc_no_grow",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "max(max_over_time(node_zfs_arc_arc_no_grow{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "arc_no_grow"
    }
   ]
  },
  {
   "title": "ARC evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(node_zfs_arc_deleted{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    }
   ]
  },
  { "title": "L2ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "L2ARC evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_zfs_arc_evict_l2_cached{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "l2_cached"
    },
    {
     "expr": "sum(rate(node_zfs_arc_evict_l2_eligible{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "l2_eligible"
    },
    {
     "expr": "sum(rate(node_zfs_arc_evict_l2_ineligible{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "l2_ineligible"
    },
    {
     "expr": "max(node_zfs_arc_evict_l2_skip{instance=\"$instance\"})",
     "legendFormat": "l2_skip"
    },
    {
     "expr": "max(node_zfs_arc_evict_not_enough{instance=\"$instance\"})",
     "legendFormat": "not_enough"
    },
    {
     "expr": "max(node_zfs_arc_evict_skip{instance=\"$instance\"})",
     "legendFormat": "skip"
    }
   ]
  },
  {
   "title": "L2ARC size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(avg_over_time(node_zfs_arc_l2_asize{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "asize"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_l2_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "size"
    },
    {
     "expr": "max(avg_over_time(node_zfs_arc_l2_hdr_size{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "Header size"
    }
   ]
  },
  {
   "title": "L2ARC operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_zfs_arc_l2_evict_l1cached{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "evict_l1cached"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_writes_lock_retry{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write lock retry"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_evict_reading{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "evict_reading"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_feeds{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "feeds"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_writes_sent{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write sent"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_writes_done{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "writes done"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_writes_error{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "writes error"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_io_error{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "IO errors"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_cksum_bad{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Checksum errors"
    },
    {
     "expr": "sum(rate(node_zfs_arc_l2_abort_lowmem{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "abort_lowmem"
    }
   ]
  },
  {
   "title": "L2ARC speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_l2_read_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_zfs_arc_l2_write_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "ZIL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "zil - bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_zfs_zil_zil_itx_copied_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "itx_copied_bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zil_zil_itx_indirect_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "itx_indirect_bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zil_zil_itx_metaslab_normal_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "itx_metaslab_normal_bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zil_zil_itx_metaslab_slog_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "itx_metaslab_slog_bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zil_zil_itx_needcopy_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "itx_needcopy_bytes"
    }
   ]
  },
  {
   "title": "zil - count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_commit_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "commit_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_commit_writer_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "commit_writer_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_copied_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_indirect_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_indirect_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_normal_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_normal_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_metaslab_slog_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_metaslab_slog_count"
    },
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "itx_needcopy_count"
    }
   ]
  }
 ]
}