---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-operator
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    operator:
      enabled: true
      replicaCount: 1
      image:
        repository: bitnami/grafana-operator
        tag: 4.4.1
      scanNamespaces:
        - monitoring
        - historian
      podSecurityContext:
        fsGroup: 568
    grafana:
      enabled: false
