---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    env:
      TZ: ${TZ}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto-config
    service:
      main:
        annotations:
          coredns.io/hostname: "mqtt.p.lan.${SECRET_DOMAIN}"
          metallb.universe.tf/loadBalancerIPs: ${SVB_LB_MOSQUITO}
        type: LoadBalancer
        externalTrafficPolicy: Local
    auth:
      enabled: true
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      configinc:
        enabled: true
        type: configMap
        mountPath: /mosquitto/configinc
        name: mqtt-conf
      mosquitto-pwd:
        enabled: true
        type: secret
        mountPath: /mosquitto/configinc/auth
        name: mosquitto-pwd
