apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - secret.sops.yaml
  - helm-release.yaml
namespace: home
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: mqtt-conf
    files:
      - mqtt.conf
