---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.1@sha256:23bba35fdbebc32705953fb5d210c4eab50a5cca39efcd65a5533067eb43a1ba
    env:
      TZ: "${TZ}"
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_LB_JELLYFIN}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.p.lan.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      transcode:
        enabled: true
        type: emptyDir
      television:
        enabled: true
        type: nfs
        server: 10.1.10.10
        path: /mnt/zstore/media/television
        mountPath: /mnt/media/television
        readOnly: true
      television-uhd:
        enabled: true
        readOnly: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.1.10.10
            path: /mnt/zstore/media/television-uhd
        mountPath: /mnt/media/television-uhd
      movies:
        enabled: true
        readOnly: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.1.10.10
            path: /mnt/zstore/media/movies
        mountPath: /mnt/media/movies
      movies-uhd:
        enabled: true
        readOnly: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.1.10.10
            path: /mnt/zstore/media/movies-uhd
        mountPath: /mnt/media/movies-uhd
      music:
        enabled: true
        readOnly: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.1.10.10
            path: /mnt/zstore/media/music
        mountPath: /mnt/media/music
      pvr:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.1.10.10
            path: /mnt/zstore/media/pvr
        mountPath: /mnt/media/pvr
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 6000Mi
