---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/rook-ceph/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: csi-addons-controller-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/rook-ceph/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: rook-ceph
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-addons
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/rook-ceph/rook-ceph/addons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
