---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - kube-prometheus
  - loki
  - vector
  - grafana
  - generic-rules
  - botkube
  - cloudflare-exporter
