---
services:
  tvh:
    image: ghcr.io/linuxserver/tvheadend:latest@sha256:e8715f103ba15eafe360e1c4257dfe8e015e80401bd9ba71bc7663b328e8e9ca
    container_name: tvheadend
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: host
    volumes:
      - /opt/docker/tvh/data:/config
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
