---
services:
  tvh:
    image: ghcr.io/linuxserver/tvheadend:latest@sha256:04caf2d70776233154fff1a184647c72068b3aa1593f3576c1c9ea3a755ae18c
    container_name: tvheadend
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: host
    volumes:
      - /opt/docker/tvh/data:/config
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
