---
services:
  tvh:
    image: ghcr.io/linuxserver/tvheadend:latest@sha256:708222e2a9374b3812cd533878dac30920dc8feb3b7ed3714a449588f4dbef9f
    container_name: tvheadend
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: host
    volumes:
      - /opt/docker/tvh/data:/config
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
