---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/darkstar/k8s/apps/system-controllers/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  timeout: 2m
