---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 15m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 50
      strategy: rollback
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    cluster:
      name: "${CLUSTER_NAME}"
    rollOutCiliumPods: true
    enableCiliumEndpointSlice: true
    localRedirectPolicy: true
    kubeProxyReplacement: "probe"
    ipv4NativeRoutingCIDR: "${NETWORK_K8S_CLUSTER_CIDR}"
    k8sServiceHost: "${CONTROL_PLANE_ENDPOINT}"
    k8sServicePort: 6443
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
    tunnel: "disabled"
    endpointRoutes:
      enabled: true
    autoDirectNodeRoutes: true
    ipam:
      mode: "kubernetes"
    ipv6:
      enabled: false
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    containerRuntime:
      integration: containerd
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          className: "nginx"
          hosts:
            - &host "hubble.p.lan.${SECRET_DOMAIN}"
          tls:
            - secretName: *host
              hosts:
                - *host
    bgp:
      enabled: false
