---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kopia-cronjobs
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/system/kopia-cronjobs/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
