---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-secret
            namespace: external-secrets
            key: client_id
          clientSecret:
            name: infisical-secret
            namespace: external-secrets
            key: client_token
      secretsScope:
        projectSlug: k8s-home-ops-g-q3-y
        environmentSlug: prod
