---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: infisical-secret
  data:
    - secretKey: client_id
      remoteRef:
        key: /darkstar/k8s/INFISICAL_CLIENT_ID
    - secretKey: client_token
      remoteRef:
        key: /darkstar/k8s/INFISICAL_AUTH_TOKEN
