---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .tunnel_account_id "t" .tunnel_id "s" .tunnel_secret) | b64enc }}
  dataFrom:
    - extract:
        key: /darkstar/k8s/CLOUDFLARE
