---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    adminUser:
      create: true
      username: localadmin
    ingress:
      enabled: true
      className: ingress-nginx-int
      hosts:
        - host: &host "gitops.${SECRET_DOMAIN_PROXY}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    podLabels:
      egress.home.arpa/apiserver: allow
      egress.home.arpa/internet: allow
      egress.home.arpa/kubedns: allow # TODO: Remove when clusterNetworkPolicy is in place
      ingress.home.arpa/nginx-internal: allow
  valuesFrom:
    - kind: Secret
      name: weave-gitops
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash
