---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2022.5.1
    env:
      TZ: ${TZ}
      ESPHOME_DASHBOARD_USE_PING: true
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "esphome.p.lan.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "esphome.p.lan.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1000Mi
