---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-localpv
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/darkstar/k8s/apps/openebs/zfs-localpv/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: csi-addons-controller-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-localpv-storage
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/darkstar/k8s/apps/openebs/zfs-localpv/storage"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: zfs-localpv
