---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ignition
resources:
  - ./namespace.yaml
#  - ./ignition/ks.yaml
#  - ./database/ks.yaml
#  - ./backend/ks.yaml
#  - ./frontend/ks.yaml
components:
  - ../../components/alerts
  - ../../components/kopiur/secret
