---
customization:
  extraKernelArgs:
    - nvme_core.default_ps_max_latency_us=5500
    - pci=noaer
    - -lockdown
    - lockdown=integrity
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/nfsrahead
