---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-stirling-pdf
  namespace: flux-system
spec:
  path: ./clusters/compute/k8s/apps/default/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
