---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kopiur
  namespace: &namespace storage
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kopiur
      namespace: storage
  interval: 1h
  path: "./kubernetes/darkstar/apps/storage/kopiur/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      APP: *appname
  dependsOn:
    - name: openebs
      namespace: storage
    - name: topolvm
      namespace: storage
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kopiur-repository
  namespace: &namespace storage
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: ClusterRepository
      name: nas
  interval: 1h
  path: "./kubernetes/darkstar/apps/storage/kopiur/repository"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
    namespace: flux-system
  wait: false
  dependsOn:
    - name: volsync
      namespace: storage
