---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-uhd-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name radarr-uhd
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi
