---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  IP_ADDR_LAN_GW: 10.1.10.1
  IP_ADDR_LAN_NAS: 10.1.10.10
  IP_ADDR_IOT_ZIGBEE: 10.1.20.101
  METALLB_LB_RANGE: 10.1.10.30-10.1.10.49
  SVC_LB_INGRESS_NGINX: 10.1.10.30
  SVC_LB_INGRESS_NGINX_EXT: 10.1.10.31
  SVC_LB_PLEX: 10.1.10.32
  SVC_LB_HASS: 10.1.10.33
  SVB_LB_MOSQUITO: 10.1.10.34
  SVC_LB_JELLYFIN: 10.1.10.35
  SVC_LB_SYSLOG: 10.1.10.48
  SVC_LB_K8S_GATEWAY: 10.1.10.49
  NETWORK_HOME_CIDR: 10.1.10.0/23
  NETWORK_K8S_CLUSTER_CIDR: 10.200.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.210.0.0/16
  TZ: Europe/London
