---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      data:
        HASS_LATITUDE: "{{ .latitude }}"
        HASS_LONGITUDE: "{{ .longitude }}"
        HASS_ELEVATION: "{{ .elevation }}"
        HASS_HIVE_USERNAME: "{{ .hive_user }}"
        HASS_HIVE_PASSWORD: "{{ .hive_pass }}"
        HASS_LG_OLED_MAC: "{{ .lg_oled_mac }}"
        HASS_ALEXA_CLIENT_ID: "{{ .alexa_client_id }}"
        HASS_ALEXA_CLIENT_SECRET: "{{ .alexa_client_secret }}"
        HA_LONG_LIVED_TOKEN: "{{ .presence_token }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/HASS
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-matter
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: home-assistant-matter-secret
    creationPolicy: Owner
    template:
      data:
        HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "{{ .matter_hub }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/HASS
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-ai
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: home-assistant-ai-secret
    creationPolicy: Owner
    template:
      data:
        STT_OPENAI_KEY: "{{ .openai_voice_key }}"
        TTS_OPENAI_KEY: "{{ .openai_voice_key }}"
        AZURE_SUBSCRIPTION_KEY: "{{ .azure_voice_key }}"
        AZURE_SERVICE_REGION: "{{ .azure_service_region }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/OPENAI
      rewrite:
        - regexp:
            source: "(.*)"
            target: "openai_$1"
    - extract:
        key: /darkstar/k8s/AZURE
      rewrite:
        - regexp:
            source: "(.*)"
            target: "azure_$1"
