---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    global:
      nameOverride: *app
    image:
      repository: jacobalberty/unifi
      tag: v7.1.66
    env:
      TZ: "${TZ}"
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${SVB_LB_UNIFI}
          metallb.universe.tf/allow-shared-ip: unifi
        type: LoadBalancer
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "{{ .Release.Name }}.p.lan.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
    resources:
      requests:
        memory: 2Gi
        cpu: 100m
