---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname weave-gitops
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/darkstar/k8s/apps/flux-system/weave-gitops/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
