# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: downloads
type: Opaque
stringData:
    RADARR_APIKEY: ENC[AES256_GCM,data:PqYvtKU8Dn9x+T998U34DE5yhHovHKT2XqJyIoSU5B4=,iv:XdjEftG7XzE/3yzAHu7WAzIVAAAx7UUdEoN7A5DtvZs=,tag:bQjR3zn3x7CN3KWBTYfktg==,type:str]
    RADARR_UHD_APIKEY: ENC[AES256_GCM,data:3ERz8j0zK3cUwNx16xnTGHJxtBjCCMhYLX3Ojdznddc=,iv:KkaHPEAEsNbrso1LzS0w7ao/7U1JjMbeR0QfT881FgU=,tag:H9u7n63bPPGoNULUl+grLw==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:CZojAre5z+xvzDVNMQ3R7qpmI5KTBGMO2ffjOGp8gZg=,iv:mOgKOYaf7xal1xg4N0p6rVCam312bkGvWwcMGlxqAjE=,tag:/mFEdHcT+TSN3LkVf0UZ+Q==,type:str]
    SONARR_UHD_APIKEY: ENC[AES256_GCM,data:GfGGJRdbredfI4d/pclIkzAsaU6JJaZR3EWcTg/+ThE=,iv:h3pmzKch5Uk6o/BBO9eVgGpcHXD+du0h2Qh5Pk+26t4=,tag:pqLomvKdX3i5MFHuFCklGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-29T23:40:32Z"
    mac: ENC[AES256_GCM,data:jl1JtPGIKsZn22cXS0uTEfgOGedH4AFU9YLrnISnW1q5J5IhT88oGh51j8K1bKYLhBvf7Kk/bdPO+mNv9/9K4QmjJ3Xvbsl6tbmPcW6Onuqwwt6CNspxDTu6d4WARpserEKQ0QymfJq1fp4Kn6pMXt7dRJbLLu1EzDZNV/RZd6g=,iv:aTQ6ihXuotaS9enqAy/OM/zmZccuenkuDLxNvRBszX8=,tag:jvRgGsGs4AQpiQPMQH+y9w==,type:str]
    pgp:
        - created_at: "2022-05-29T23:40:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1fr/5wrlRWyARAAFm/4fp3HtNZkV3Di+auouYhOA16l2P+o/YGW2vV7luez
            DzCC6lEDI55gB0lqkGseLroYV2PjCVGqBLsc6TPRgBAvocwaGT7FpxeWY7K49mRb
            SlPM+GsYi6qcebKu459mwcdkqVE/VxhBr09EYwAv+FpxZQplS89bLUwblpJsfE7E
            0y3i+dn/TaPNvDOI7u2Cf6tvu4zCCE+/PkOaNZ0OQNJ5fkwMUgkFpqdGeX+R68kc
            6gJurnDSiZy7stSply2JfQFchMUkp1VXfG/5sxk4BG4SAUK/1XBxbIJiq1xjYeFR
            adqhDtQQ8LQfepNwDvO897rPU3PxtrYKFz+WSQuble3qhRMN5tSajvXBZIrXCxzg
            9KrGH8YIOIDNoDHPg+NbYgT96v5EHHCDNzsqG8UV09bWrzwgp+W3HMsEKRNS/Dh3
            QoxuHa+8uP3rsiiUMpOOr4sB+MLkh0+jQH/kpZdtOhNrpIflNUFVcuDDr4aG5Yol
            6VHIXPk/8g8ZKFz40G79Z0a8hPkRJ+SXfCkKeoVdgabqTDo8DwXhj4n+BGED+CqZ
            9QK0KMCIQUkp3VKrlCQClCFvdpuf3dMSb3yyijdAaSBMo4zqEnThcq2VOzDeTKUY
            kh55xoJ4BgPwrM0Lk7ZIjXp8PPCUs2wJ1Gj89EL6yfLWGUl/1rQWhxgImzxmC5XS
            5gHJCJM32BfkJO3skCtMZqNQAKjFYBFzvWueWTUHGJ5XCVNPm/MvZxtCrErrWB5T
            nIm3twvCMyvQekt1dqCNoLLkuwDKOsre2/2/E+ZcPQ0GnuIjv5NJAA==
            =0zBK
            -----END PGP MESSAGE-----
          fp: 4CF588582D481BB5C1927F275BB27F59F87ABCA3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
