---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mass-alexa
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mass-alexa-secret
    creationPolicy: Owner
    template:
      data:
        APP_USERNAME: "{{ .app_username }}"
        APP_PASSWORD: "{{ .app_password }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/MASS
