---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tautulli
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/tautulli
      tag: v2.10.1
    env:
      TZ: "${TZ}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "tautulli.p.lan.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tautulli.p.lan.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config
    podSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
