# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ksi-vm-sim01
  namespace: flux-system
spec:
  targetNamespace: vms
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/kvm/vms/windows/ksi-vm-sim01"
  prune: false
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  dependsOn:
    - name: kubevirt
    - name: cdi
    - name: democratic-csi-zfs-local-dataset
    - name: vms-common
