---
services:
  hawser:
    image: ghcr.io/finsys/hawser:0.2.43
    container_name: hawser
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - STACKS_DIR=/opt/hawser-stacks
    ports:
      - 2376:2376
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker:/opt/hawser-stacks
