---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.20.21/24"]
              }]
          labels:
            ingress.home.arpa/nginx-internal: allow
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
        containers:
          main:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2023.12.9
            env:
              ESPHOME_DASHBOARD_USE_PING: true
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 1000Mi
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        className: ingress-nginx-int
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN_PROXY}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
