---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-alpha
parameters:
  recordsize: 4k
  compression: off
  dedup: off
  fstype: zfs
  poolname: alpha/k8s/local/v
reclaimPolicy: Retain
allowVolumeExpansion: true
provisioner: zfs.csi.openebs.io
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - alpha
