directories:
  downloads: /media/.downloads/soulseek/complete
  incomplete: /media/.downloads/soulseek/incomplete
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
shares:
  directories:
    - /media/soulseek
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
transfers:
  download:
    destination:
      permissions:
        mode: 750
    retry:
      partial: resume
      attempts: 3
      delay: 5000
      max_delay: 60000
web:
  authentication:
    api_keys:
      default:
        key: ${SLSKD_API_KEY}
        cidr: 0.0.0.0/0,::/0
