---
apiVersion: v1
kind: Secret
metadata:
  name: esphome-restic-secret
  namespace: home
stringData:
  RESTIC_REPOSITORY: "s3:${R2_REPOSITORY}/volsync/esphome"
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: esphome
  namespace: home
spec:
  sourcePVC: config-esphome-0
  trigger:
    schedule: "0 5 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: esphome-restic-secret
    retain:
      daily: 7
      within: 3d
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    volumeSnapshotClassName: zfs-local-dataset
    storageClassName: zfs-local-dataset
    cacheCapacity: 3G
    cacheStorageClassName: local-hostpath
---
apiVersion: v1
kind: Secret
metadata:
  name: esphome-restic-secret-minio
  namespace: home
stringData:
  RESTIC_REPOSITORY: "s3:${MINIO_REPOSITORY}/volsync/esphome"
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: esphome-minio
  namespace: home
spec:
  sourcePVC: config-esphome-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    repository: esphome-restic-secret-minio
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    volumeSnapshotClassName: zfs-local-dataset
    storageClassName: zfs-local-dataset
    cacheCapacity: 1G
    cacheStorageClassName: local-hostpath
