---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kvm-cdi
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  interval: 5m
  prune: true
  wait: true
  path: "./deploy"
  sourceRef:
    kind: GitRepository
    name: cdi
  dependsOn: []
  patches:
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cdi
      target:
        kind: Namespace
        name: cdi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kvm-cdi-manifests
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  path: "./clusters/compute/k8s/kvm/cdi/app/manifests"
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  dependsOn:
    - name: cluster-kvm-cdi
