---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname mosquitto
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/apps/home-automation/mosquitto/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substitute:
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CLAIM: mosquitto-data
      VOLSYNC_CAPACITY: 256Mi
  dependsOn:
    - name: rook-ceph-cluster
    - name: multus-config
    - name: volsync
    - name: k8tz
