---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: zfs-local-dataset
              globalMounts:
                - path: /alertmanager
        containers:
          main:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: main@sha256:0cdde08a824cce3c1fb51c2464030cb2db6283f3a598861c7b8940e0110af4fe
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M
    service:
      main:
        ports:
          http:
            port: 9093
    ingress:
      main:
        enabled: true
        className: ingress-nginx-int
        hosts:
          - host: &host "alert-manager.${SECRET_DOMAIN_PROXY}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: alertmanager-configmap
        globalMounts:
          - path: /etc/alertmanager
            readOnly: true
