---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # TODO: Remove when clusterNetworkPolicy is in place
          securityContext:
            runAsNonRoot: true
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 6.0.2
            env:
              SONARR_API_KEY: ${SONARR_API_KEY}
              RADARR_API_KEY: ${RADARR_API_KEY}
            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        advancedMounts:
          main:
            init-config:
              - path: /tmp/config
                readOnly: true
    service:
      main:
        enabled: false
