---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      main:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "@daily"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 6.0.2
            args:
              - sync
            env:
              COMPlus_EnableDiagnostics: "0"
              SONARR_API_KEY: ${SONARR_API_KEY}
              RADARR_API_KEY: ${RADARR_API_KEY}
            resources:
              requests:
                cpu: 5m
                memory: 50M
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        advancedMounts:
          main:
            init-config:
              - path: /config/recyclarr.yml
                subPath: recyclarr.yml
                readOnly: true
    service:
      main:
        enabled: false
