---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  # PVC and volsync templates
  - ../../../../templates/volsync
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
