---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: rook-ceph
  interval: 10m
  path: "./clusters/compute/k8s/apps/rook-ceph/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: rook-ceph-cluster
  interval: 10m
  path: "./clusters/compute/k8s/apps/rook-ceph/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph
    - name: cluster-apps-snapshot-controller
