---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: slskd
spec:
  staticConfigs:
    - targets:
        - "slskd.starstreak.net"
  metricsPath: /metrics
  scheme: HTTPS
