---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rfc2136-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rfc2136-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: tsig_key
      remoteRef:
        key: /darkstar/k8s/TECHNITIUM
