---
services:
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    container_name: smartctl-exporter
    restart: always
    ports:
      - 9633:9633
    privileged: true
    user: root
