---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.2.2
            envFrom:
              - secretRef:
                  name: home-assistant
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 126m
                memory: 512M
              limits:
                memory: 2048M
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.21.1@sha256:c9f78fb7e8ac5fdd3bea856142dd5c5dda0f5183131254516af74135dc97c773
              pullPolicy: IfNotPresent
            env:
              HASS_SERVER: http://localhost:8123
            args:
              - --user-data-dir
              - "/config/.vscode"
              - --auth
              - "none"
              - --port
              - "12321"
              - "/config"
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_LB_HASS}
        ports:
          http:
            port: 8123
            primary: true
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 12321
            protocol: TCP
    ingress:
      main:
        enabled: true
        className: ingress-nginx-ext
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        enabled: true
        className: ingress-nginx-int
        hosts:
          - host: &host "hass-vscode.${SECRET_DOMAIN_PROXY}"
            paths:
              - path: /
                service:
                  name: codeserver
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
