---
- name: Install docker, doco-cd and config
  hosts: nas
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    docker_compose_service_base_dir: "{{ docker_base_dir }}"

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker

  handlers:
    - name: Restart docker-cleanup
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
        daemon_reload: true
      loop:
        - docker-cleanup.service
        - docker-cleanup.timer

  tasks:
    - name: Create default directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: users
        mode: "0775"
      loop:
        - "{{ docker_base_dir }}"
      tags:
        - always

    - name: Ensure docker.service.d directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "0755"

    - name: Create docker clean up systemd files
      notify: Restart docker-cleanup
      ansible.builtin.copy:
        src: "{{ ansible_files_dir }}/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        mode: "0644"
        remote_src: false
      loop:
        - docker-cleanup.service
        - docker-cleanup.timer

    # Ensure docker starts after zfs is available
    - name: Create docker override systemd file
      ansible.builtin.copy:
        src: "{{ ansible_files_dir }}/docker-override.conf"
        dest: "/etc/systemd/system/docker.service.d/override.conf"
        mode: "0644"
        remote_src: false

    - name: Read secrets from Infisical
      ansible.builtin.shell: "infisical secrets get --plain --env=prod --path=/apollo/docker '{{ item.key }}' < /dev/null"
      delegate_to: localhost
      become: false
      loop:
        - key: DOCO_CD_INFISICAL_TOKEN
          var: doco_infisical_secret
        - key: DOCO_CD_API_TOKEN
          var: doco_api_secret
        - key: DOCO_CD_WEBHOOK_TOKEN
          var: doco_webhook_secret
      check_mode: false
      changed_when: false
      no_log: true
      register: secrets_raw

    - name: Set secret facts
      ansible.builtin.set_fact:
        doco_infisical_secret: "{{ secrets_raw.results[0].stdout }}"
        doco_api_secret: "{{ secrets_raw.results[1].stdout }}"
        doco_webhook_secret: "{{ secrets_raw.results[2].stdout }}"
      no_log: true

    - name: Setup doco-cd
      vars:
        dococd_dir: /opt/docker/doco-cd
      block:
        - name: Create doco-cd folder
          ansible.builtin.file:
            path: "{{ dococd_dir }}"
            state: directory
            owner: localadmin
            group: localadmin
            mode: "0700"

        - name: Create doco-cd config folder
          ansible.builtin.file:
            path: "{{ dococd_dir }}/.config"
            state: directory
            owner: localadmin
            group: localadmin
            mode: "0700"

        - name: Copy docker-compose app file
          ansible.builtin.copy:
            src: "./files/docker-compose.yaml"
            dest: "{{ dococd_dir }}/docker-compose.yaml"
            mode: "0644"
            owner: localadmin
            group: localadmin
          register: compose_file

        - name: Create secrets
          ansible.builtin.copy:
            dest: "{{ dococd_dir }}/.config/{{ item.name }}"
            content: |
              {{ item.content }}
            owner: localadmin
            group: localadmin
            mode: "0600"
          no_log: true
          loop:
            - name: infisical_secret
              content: "{{ doco_infisical_secret }}"
            - name: api_secret
              content: "{{ doco_api_secret }}"
            - name: webhook_secret
              content: "{{ doco_webhook_secret }}"

        - name: Run docker-compose
          community.docker.docker_compose_v2:
            project_src: "{{ dococd_dir }}"
            files:
              - docker-compose.yaml
            pull: always
            state: present
          when: not ansible_check_mode

        - name: Wait for healthy
          community.docker.docker_container_info:
            name: doco-cd
          register: dococd_info
          until: dococd_info.container.State.Health.Status == "healthy"
          retries: 30
          delay: 10
          when: not ansible_check_mode
