---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname prowlarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/apps/downloads/prowlarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CLAIM: prowlarr-config
      VOLSYNC_CAPACITY: 1Gi
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
    - name: k8tz
