---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - cert-manager
  - default
  - downloads
  - flux-system
  - home
  - kube-system
  - kyverno
  - media
  - monitoring
  - networking
  - system
