---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  data:
    - secretKey: PROWLARR__AUTH__APIKEY
      remoteRef:
        key: /darkstar/k8s/PROWLARR_AUTH_APIKEY
