---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      data:
        FRIGATE_CAM_USER: "{{ .camera_user }}"
        FRIGATE_CAM_PASSWORD: "{{ .camera_pass }}"
        PLUS_API_KEY: "{{ .plus_api_key }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/FRIGATE
