---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-issuer
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-issuer-secret
    template:
      data:
        cf-token: "{{ .token_certmanager }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/CLOUDFLARE
