external_secrets:
  SABNZBD_API_KEY: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_API_KEY
  SABNZBD_SERVER_1: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_1
  SABNZBD_SERVER_1_USER: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_1_USER
  SABNZBD_SERVER_1_PASS: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_1_PASS
  SABNZBD_SERVER_2: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_2
  SABNZBD_SERVER_2_USER: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_2_USER
  SABNZBD_SERVER_2_PASS: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/SABNZBD_SERVER_2_PASS
