---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-02-17T01-15-57Z
            args:
              - server
              - /data
              - --console-address
              - :9001
            env:
              MINIO_PROMETHEUS_JOB_ID: *app
              MINIO_PROMETHEUS_AUTH_TYPE: "public"
              MINIO_UPDATE: "off"
            envFrom:
              - secretRef:
                  name: minio-secret
            resources:
              requests:
                cpu: 5m
                memory: 128M
            securityContext:
              privileged: true
              runAsUser: 0
    service:
      main:
        ports:
          http:
            port: 9001
          s3:
            port: 9000
    ingress:
      main:
        enabled: true
        className: ingress-nginx-int
        hosts:
          - host: &minio "minio.${SECRET_DOMAIN_PROXY}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: &s3 "s3.${SECRET_DOMAIN_PROXY}"
            paths:
              - path: /
                service:
                  name: main
                  port: s3
        tls:
          - hosts:
              - *minio
              - *s3
    persistence:
      dev:
        type: hostPath
        hostPath: /var/mnt/usb/minio
        hostPathType: Directory
        globalMounts:
          - path: /data
