---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false # no flux ks dependents
  dependsOn:
    - name: rook-ceph-cluster
    - name: kube-prometheus-stack
    - name: k8tz
