---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: openebs
spec:
  interval: 15m
  releaseName: zfs-localpv
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/zfs-localpv
      chart: zfs-localpv
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: zfs-localpv-charts
        namespace: flux-system
      interval: 15m
