---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: cluster-apps-nginx-internal
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
