---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ingress-nginx-int
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  dependsOn:
    - name: cert-manager-issuers
    - name: k8tz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ingress-nginx-ext
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  dependsOn:
    - name: ingress-nginx-int
