---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-block-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.5
      sourceRef:
        name: democratic-csi-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.ceph-block"
      attachRequired: false
      storageCapacity: true # With storage capacity tracking, the scheduler filters out nodes which do not have enough capacity.
      fsGroupPolicy: File # fsGroupChangePolicy
    storageClasses:
      - name: ceph-block
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        # distributed support is not yet ready for expansion
        allowVolumeExpansion: false
    controller:
      enabled: true
      strategy: node
      externalAttacher:
        enabled: false
      externalProvisioner:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalSnapshotter:
        enabled: true
    driver:
      config:
        driver: ceph-block
        zfs:
          datasetParentName: alpha/k8s/local/v
          detachedSnapshotsDatasetParentName: alpha/k8s/local/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
