external_secrets:
  CLOUDFLARE_DNS: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/CLOUDFLARE_DNS
  ADGUARD_USER: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/ADGUARD_USER
  ADGUARD_PASSWORD: 7ada94fa-d930-4461-83ca-5eb11a28b33f:prod:/apollo/docker/ADGUARD_PASSWORD
