---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname democratic-csi-local-path
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./clusters/compute/k8s/apps/system/democratic-csi/local-path"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname democratic-csi-zfs-local-dataset
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./clusters/compute/k8s/apps/system/democratic-csi/zfs-local-dataset"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname democratic-csi-zfs-local-zvol
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./clusters/compute/k8s/apps/system/democratic-csi/zfs-local-zvol"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  interval: 10m
  wait: true
