---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ksi-vm-sim01-c-drive
spec:
  storageClassName: ceph-block
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "150Gi"
