---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: &app ksi-vm-sim01
  labels:
    special: *app
spec:
  preference:
    kind: VirtualMachinePreference
    name: vm-windows
  instancetype:
    kind: VirtualMachineInstancetype
    name: vm-windows
  runStrategy: Manual
  template:
    metadata:
      labels:
        vm.home.arpa/os: windows
        vm.home.arpa/windows: *app
    spec:
      hostname: *app
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        devices:
          disks:
            - name: windows-iso
              cdrom:
                bus: sata
            - name: c-drive
              disk: {}
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
          interfaces:
            - name: default
              model: e1000
              masquerade: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          uuid: f68c22f6-5c82-4744-947c-9704998e8ce7
          bootloader:
            efi:
              secureBoot: true
      networks:
        - name: default
          pod: {}
      volumes:
        - name: c-drive
          persistentVolumeClaim:
            claimName: ksi-vm-sim01-c-drive
        - name: windows-iso
          persistentVolumeClaim:
            claimName: vm-cdrom-windows11
        - name: virtiocontainerdisk
          persistentVolumeClaim:
            claimName: vm-cdrom-virtio-win
