---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: &app ksi-vm-sim01
  labels:
    special: *app
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        vm.home.arpa/os: windows
        vm.home.arpa/windows: *app
    spec:
      hostname: *app
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 3
        devices:
          autoattachInputDevice: false # save CPU resources, similar to disabling tablet input on Proxmox
          disks:
            - name: windows-iso
              cdrom:
                bus: sata
            - name: c-drive
              disk:
                bus: sata
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
          interfaces:
            - name: default
              model: e1000
              masquerade: {}
          tpm:
            persistent: true
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          uuid: ${KV_KSI_VM_SIM01_UUID}
          serial: ${KV_KSI_VIM_SIM01_SERIAL}
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 16Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: c-drive
          persistentVolumeClaim:
            claimName: ksi-vm-sim01-c-drive
        - name: windows-iso
          persistentVolumeClaim:
            claimName: vm-cdrom-windows11
        - name: virtiocontainerdisk
          persistentVolumeClaim:
            claimName: vm-cdrom-virtio-win
