---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: zfs-localpv-charts
        namespace: flux-system
      interval: 30m
