apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"tigera-operator","namespace":"tigera-operator"}}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:26:32Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: tigera-operator
      helm.toolkit.fluxcd.io/namespace: tigera-operator
    name: tigera-operator
    namespace: tigera-operator
    resourceVersion: "5089067"
    uid: 50bbc06b-55f5-4aa5-ba13-d4c187233ac2
- apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"policy/v1beta1","kind":"PodSecurityPolicy","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator","seccomp.security.alpha.kubernetes.io/allowedProfileNames":"*"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"tigera-operator"},"spec":{"allowPrivilegeEscalation":false,"fsGroup":{"ranges":[{"max":65535,"min":1}],"rule":"MustRunAs"},"hostIPC":false,"hostNetwork":true,"hostPID":false,"hostPorts":[{"max":65535,"min":0}],"privileged":false,"readOnlyRootFilesystem":false,"requiredDropCapabilities":["ALL"],"runAsUser":{"rule":"MustRunAsNonRoot"},"seLinux":{"rule":"RunAsAny"},"supplementalGroups":{"ranges":[{"max":65535,"min":1}],"rule":"MustRunAs"},"volumes":["hostPath","configMap","emptyDir","projected","secret","downwardAPI","persistentVolumeClaim"]}}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    creationTimestamp: "2022-07-21T14:24:30Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: tigera-operator
      helm.toolkit.fluxcd.io/namespace: tigera-operator
    name: tigera-operator
    resourceVersion: "5089066"
    uid: 914fdc50-5de9-4912-92b7-18837759fe6b
  spec:
    allowPrivilegeEscalation: false
    fsGroup:
      ranges:
      - max: 65535
        min: 1
      rule: MustRunAs
    hostNetwork: true
    hostPorts:
    - max: 65535
      min: 0
    requiredDropCapabilities:
    - ALL
    runAsUser:
      rule: MustRunAsNonRoot
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      ranges:
      - max: 65535
        min: 1
      rule: MustRunAs
    volumes:
    - hostPath
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
    - persistentVolumeClaim
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"tigera-operator"},"rules":[{"apiGroups":[""],"resources":["namespaces","pods","podtemplates","services","endpoints","events","configmaps","secrets","serviceaccounts"],"verbs":["create","get","list","update","delete","watch"]},{"apiGroups":[""],"resources":["resourcequotas"],"verbs":["list","get","watch"]},{"apiGroups":[""],"resourceNames":["calico-critical-pods","tigera-critical-pods"],"resources":["resourcequotas"],"verbs":["create","get","list","update","delete","watch"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get","patch","list","watch"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["clusterroles","clusterrolebindings","rolebindings","roles"],"verbs":["create","get","list","update","delete","watch","bind","escalate"]},{"apiGroups":["apps"],"resources":["deployments","daemonsets","statefulsets"],"verbs":["create","get","list","patch","update","delete","watch"]},{"apiGroups":["apps"],"resourceNames":["tigera-operator"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":["operator.tigera.io"],"resources":["*"],"verbs":["create","get","list","update","patch","delete","watch"]},{"apiGroups":["networking.k8s.io"],"resources":["networkpolicies"],"verbs":["create","update","delete","get","list","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["felixconfigurations"],"verbs":["create","patch","list","get","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["ippools","kubecontrollersconfigurations","bgpconfigurations"],"verbs":["get","list","watch"]},{"apiGroups":["scheduling.k8s.io"],"resources":["priorityclasses"],"verbs":["create","get","list","update","delete","watch"]},{"apiGroups":["policy"],"resources":["poddisruptionbudgets"],"verbs":["create","get","list","update","delete","watch"]},{"apiGroups":["apiregistration.k8s.io"],"resources":["apiservices"],"verbs":["list","watch","create","update"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create","get","list","update","delete","watch"]},{"apiGroups":["policy"],"resourceNames":["tigera-operator"],"resources":["podsecuritypolicies"],"verbs":["use"]},{"apiGroups":["policy"],"resources":["podsecuritypolicies"],"verbs":["get","list","watch","create","update","delete"]},{"apiGroups":["certificates.k8s.io"],"resources":["certificatesigningrequests"],"verbs":["list"]}]}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:24:30Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: tigera-operator
      helm.toolkit.fluxcd.io/namespace: tigera-operator
    name: tigera-operator
    resourceVersion: "5089068"
    uid: c69fa539-5958-4170-b5a1-7779a7bf2ff7
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - pods
    - podtemplates
    - services
    - endpoints
    - events
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
  - apiGroups:
    - ""
    resources:
    - resourcequotas
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - calico-critical-pods
    - tigera-critical-pods
    resources:
    - resourcequotas
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - patch
    - list
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    - clusterrolebindings
    - rolebindings
    - roles
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
    - bind
    - escalate
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - statefulsets
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - delete
    - watch
  - apiGroups:
    - apps
    resourceNames:
    - tigera-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - operator.tigera.io
    resources:
    - '*'
    verbs:
    - create
    - get
    - list
    - update
    - patch
    - delete
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - felixconfigurations
    verbs:
    - create
    - patch
    - list
    - get
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    - kubecontrollersconfigurations
    - bgpconfigurations
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - scheduling.k8s.io
    resources:
    - priorityclasses
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
  - apiGroups:
    - apiregistration.k8s.io
    resources:
    - apiservices
    verbs:
    - list
    - watch
    - create
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
  - apiGroups:
    - policy
    resourceNames:
    - tigera-operator
    resources:
    - podsecuritypolicies
    verbs:
    - use
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    verbs:
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"tigera-operator"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"tigera-operator"},"subjects":[{"kind":"ServiceAccount","name":"tigera-operator","namespace":"tigera-operator"}]}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:24:30Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: tigera-operator
      helm.toolkit.fluxcd.io/namespace: tigera-operator
    name: tigera-operator
    resourceVersion: "5089069"
    uid: cc6e39fa-ecbd-4656-bd01-6624135ea45d
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: tigera-operator
  subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm","k8s-app":"tigera-operator"},"name":"tigera-operator","namespace":"tigera-operator"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/managed-by":"Helm","name":"tigera-operator"}},"template":{"metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm","k8s-app":"tigera-operator","name":"tigera-operator"}},"spec":{"containers":[{"command":["operator"],"env":[{"name":"WATCH_NAMESPACE","value":""},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"tigera-operator"},{"name":"TIGERA_OPERATOR_INIT_IMAGE_VERSION","value":"v1.27.7"}],"envFrom":[{"configMapRef":{"name":"kubernetes-services-endpoint","optional":true}}],"image":"quay.io/tigera/operator:v1.27.7","imagePullPolicy":"IfNotPresent","name":"tigera-operator","volumeMounts":[{"mountPath":"/var/lib/calico","name":"var-lib-calico","readOnly":true}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"tigera-operator","tolerations":[{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/calico"},"name":"var-lib-calico"}]}}}}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:26:32Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: tigera-operator
      helm.toolkit.fluxcd.io/namespace: tigera-operator
      k8s-app: tigera-operator
    name: tigera-operator
    namespace: tigera-operator
    resourceVersion: "5089070"
    uid: f299e6a7-6200-4c66-ba0c-4d509e49d22c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/managed-by: Helm
        name: tigera-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          meta.helm.sh/release-name: tigera-operator
          meta.helm.sh/release-namespace: tigera-operator
        creationTimestamp: null
        labels:
          app.kubernetes.io/managed-by: Helm
          k8s-app: tigera-operator
          name: tigera-operator
      spec:
        containers:
        - command:
          - operator
          env:
          - name: WATCH_NAMESPACE
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: tigera-operator
          - name: TIGERA_OPERATOR_INIT_IMAGE_VERSION
            value: v1.27.7
          envFrom:
          - configMapRef:
              name: kubernetes-services-endpoint
              optional: true
          image: quay.io/tigera/operator:v1.27.7
          imagePullPolicy: IfNotPresent
          name: tigera-operator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/calico
            name: var-lib-calico
            readOnly: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: tigera-operator
        serviceAccountName: tigera-operator
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/calico
            type: ""
          name: var-lib-calico
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-07-21T14:26:32Z"
      lastUpdateTime: "2022-07-21T14:26:33Z"
      message: ReplicaSet "tigera-operator-6f999b9479" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-07-21T14:51:00Z"
      lastUpdateTime: "2022-07-21T14:51:00Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: operator.tigera.io/v1
  kind: APIServer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"APIServer","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"default"},"spec":{}}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:24:30Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: default
    resourceVersion: "5073825"
    uid: 37e3f42e-c0e7-45f7-9151-d99b5456e597
  spec: {}
  status:
    state: Ready
- apiVersion: operator.tigera.io/v1
  kind: Installation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Installation","metadata":{"annotations":{"meta.helm.sh/release-name":"tigera-operator","meta.helm.sh/release-namespace":"tigera-operator"},"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"default"},"spec":{"calicoNetwork":{"ipPools":[{"blockSize":26,"cidr":"10.200.0.0/16","encapsulation":"VXLANCrossSubnet","natOutgoing":"Enabled","nodeSelector":"all()"}],"linuxDataplane":"Iptables","multiInterfaceMode":"None","nodeAddressAutodetectionV4":{"cidrs":["10.1.10.0/24"]}},"imagePullSecrets":[],"kubernetesProvider":"","nodeMetricsPort":9091,"typhaMetricsPort":9093}}
      meta.helm.sh/release-name: tigera-operator
      meta.helm.sh/release-namespace: tigera-operator
    creationTimestamp: "2022-07-21T14:28:11Z"
    finalizers:
    - tigera.io/operator-cleanup
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
    name: default
    resourceVersion: "5072332"
    uid: 4a80d801-d939-40f7-b34c-c2368d56e9d6
  spec:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 26
        cidr: 10.200.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        cidrs:
        - 10.1.10.0/24
    cni:
      ipam:
        type: Calico
      type: Calico
    controlPlaneReplicas: 2
    flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
    imagePullSecrets: []
    kubernetesProvider: ""
    nodeMetricsPort: 9091
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    nonPrivileged: Disabled
    typhaMetricsPort: 9093
    variant: Calico
  status:
    computed:
      calicoNetwork:
        bgp: Enabled
        hostPorts: Enabled
        ipPools:
        - blockSize: 26
          cidr: 10.200.0.0/16
          encapsulation: VXLANCrossSubnet
          natOutgoing: Enabled
          nodeSelector: all()
        linuxDataplane: Iptables
        multiInterfaceMode: None
        nodeAddressAutodetectionV4:
          cidrs:
          - 10.1.10.0/24
      cni:
        ipam:
          type: Calico
        type: Calico
      controlPlaneReplicas: 2
      flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      nodeMetricsPort: 9091
      nodeUpdateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      nonPrivileged: Disabled
      typhaMetricsPort: 9093
      variant: Calico
    mtu: 1450
    variant: Calico
kind: List
metadata: {}
