---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-dns-secret
    creationPolicy: Owner
    template:
      data:
        cf_token: "{{ .token_dns }}"
  dataFrom:
    - extract:
        key: /darkstar/k8s/CLOUDFLARE
