receivers:
  - name: "null"
  - name: "discord"
    webhook_configs:
      - url: ${ALERTMANAGER_DISCORD_WEBHOOK}

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "discord"
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: "discord"
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "namespace"]
