---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./cloudflared-secret.sops.yaml
  - ./dnsEndpoint.yaml
  - ./helm-release.yaml
  - ./network-policy.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
