---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/compute/k8s/apps/networking/cloudflared/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: false
  dependsOn:
    - name: cluster-apps-k8s-ycl
    - name: cluster-apps-k8tz
