---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-repos
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/compute/k8s/repos
  prune: false
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
